### ISSUE TITLE
getCommunicationRulesDetails

### ISSUE THREAD

**Issue by guygunarathne** [TheAlphaSchoolSystemPTYLTD/student-details#10]
I am able to get student details from ‘getStudentsDetails’ API by using live credentials of my school as passed all parameters in following format:-  http://api.tasscloud.com.au/tassweb/api/?method=GetStudentsDetails&appcode=DEMOSD&company=10&v=2&token=l1D8owEn111IHcXLRwXTB0oU2GX6rj%2BISqa9zXA8We1Gqx9%2Fzb%2BcbVFartivsDN%2FxGgAIIjtABAYfzYPqTCpLf3gb0nW3h%2FTrPFLMhAdNcVvHD0Gz4FkRj5jRAD1aAGQ 

But I am facing issue to get response from ‘getCommunicationRulesDetails’ API by using same credentials. 

Sample parameters: { "currentstatus":"current", code":"20073",  "commtype":"all" } 
Getting below error response:  
![download](https://user-images.githubusercontent.com/44564157/51300937-85265380-1a53-11e9-9f4f-0538dbbb3e7b.png)

**Comment by ricardorusson** [comment]
The error suggests that the "commtype" has not been supplied. Can you confirm that the 'token' you are sending in your request is the result of encrypting your parameters with your token key?

**Comment by ricardorusson** [comment]
The tokens shouldnt be the same, as they are the result of encrypting your parameters. Since the parameters are different for the two methods, we would expect the token to also be different.

Please read through the API Introduction documentation.

https://github.com/TheAlphaSchoolSystemPTYLTD/api-introduction

**Comment by guygunarathne** [comment]
I am following this same documentation and using methods of this documentation u7j1s64F8si1JJE2DZVc7veSYISK7Xze8Q94glKm8nHueKYsSeRO5AVFQlkVS+Xn0dP9JExQSLy98RHiA0NRcatEqfbXPbxhYEiUVoqP9aM9ReHMaFsb5zmJ0hBpRVbAhiee3 for encrypting the parameters in php.

**Comment by guygunarathne** [comment]
I am following this same https://github.com/TheAlphaSchoolSystemPTYLTD/api-introduction documentation and using methods of this documentation https://github.com/TheAlphaSchoolSystemPTYLTD/api-introduction/blob/master/encryptDecrypt.php  for encrypting the parameters in php.

**Comment by guygunarathne** [comment]
> I am following this same https://github.com/TheAlphaSchoolSystemPTYLTD/api-introduction documentation and using methods of this documentation https://github.com/TheAlphaSchoolSystemPTYLTD/api-introduction/blob/master/encryptDecrypt.php for encrypting the parameters in php.

@ricardorusson can you please explore more to me about this.

**Comment by jtc** [comment]
Hey @guygunarathne,

In line 10 of https://github.com/TheAlphaSchoolSystemPTYLTD/api-introduction/blob/master/encryptDecrypt.php, a paramaters variable is declared and set.

Can you share the equivalent line of code as you have written it in your project?

Can you also confirm the school has Communication Rules enabled? Not sure if it's even possible to have it disabled these days or how the TASS API would react, just guessing here. They can check at TASS.web > Student Admin > Student Records > Setup Information > Student Records Setup. There will be a tick-box half-way down those options labelled "Enable Communication Rules".

Josh
(not a TASS employee)

**Comment by ricardorusson** [comment]
Closing issue. Please feel free to re-open if required.
Thanks.
