### ISSUE TITLE
Return class information in getStudentDetails

### ISSUE THREAD

**Issue by AbbotsleighGitHub** [TheAlphaSchoolSystemPTYLTD/student-details#15]
Similar to lms-integration/getStudentSubjects, it would be helpful to include student class enrolment in the getStudentDetails dataset. Even if this was an optional param. It would be even more helpful if the getStudentSubjects query could be filtered based on this information (e.g. load students from 07 English course, or 07 English 1 class)

**Comment by pl4nty** [comment]
Seconded. It's possible to use the [Academic Analysis API](https://github.com/TheAlphaSchoolSystemPTYLTD/student-academic-analytics) to get student codes then call getStudentDetails on each, but this approach involves heavy overhead.

Even being able to query an array of student codes (like the other APIs) would be good.

**Comment by scottetass** [comment]
Hi,

getStudentDetails has been modified as per below and these changes will be in the May Release.

```
'currentstatus': now optional, used to be mandatory.
'code': can be blank, single student code or comma delimited list of student codes.

Either 'code' or 'currentstatus' must be provided, they can't both be blank. You can provide both for filtering purposes.
```

Thanks, Scott
