### ISSUE TITLE
Version 1 and 2 methods are not accessible

### ISSUE THREAD

**Issue by richardthornton** [TheAlphaSchoolSystemPTYLTD/student-details#32]
Hi! Our request to getStudentDetails has started failing sometime over the last few days with the error:

`{"__status":"invalid","__msg":"Version 1 and 2 methods are not accessible when a Security Role has been
defined.","__invalid":{}}`

We have not made any changes to our API calls for 6+ months and this is a critical blocker for our application. Could you please let me know what we now need to do?

Thanks!

**Comment by MatthewVince** [comment]
Hi Richard,

We had the same issue with our integrations. It looks like TASS added a security role section to their API Application details screen a while back. Fortunately changing the v=2 to v=3 in the api request url fixed this issue for us.

![image](https://user-images.githubusercontent.com/70737704/96390160-d6a6d800-120f-11eb-96c1-69d07266f504.png)

![image](https://user-images.githubusercontent.com/70737704/96390181-e6beb780-120f-11eb-8333-253945aca8bd.png)

**Comment by richardthornton** [comment]
Thanks @MatthewVince. I'm a third-party dev and don't have any direct access to TASS. The schools I'm working with do a great job of helping out when I need specific details - presumably they changed this security role in their API details. This did the trick for me though, thank you!
