### ISSUE TITLE
Need "address number" added to getCommunicationRulesDetails responses

### ISSUE THREAD

**Issue by cwool** [TheAlphaSchoolSystemPTYLTD/student-details#39]
We currently are having a lot of difficulty matching the correct contact information against parents due to the API not containing the address number. There are several schools needing this which are: St Luke's Anglican College, Kennedy Baptist College and Kingsway Christian College to name a few.

Here is a screenshot of the schools view inside TASS to illustrate which number I am referring to:

![comms1](https://user-images.githubusercontent.com/70622121/117385430-71ef6880-af28-11eb-89d7-473f764fe138.jpg)

It is the number on the far left (1,3,4,5,7). We need this because the Address description (Correspondence, Billing, Parent 1... etc) are different in each school and are unreliable to match on.

We are using this method of the API: https://github.com/TheAlphaSchoolSystemPTYLTD/student-details/blob/master/getCommunicationRulesDetails.md and it does not contain the needed Address number, so can we please get this added?

**Comment by jtc** [comment]
Please be aware that address numbers can also be different in each school, for example see these two[(1)](https://hub.tassweb.com.au/confluence/help-centre/documentation/tass-web/student-admin/parent-records-par/par-setup-information/par-parent-records-setup-su/par-addresses-tab-su)[(2)](https://hub.tassweb.com.au/confluence/help-centre/documentation/how-to-checklists/how-parent-records/setting-up-parent-addresses-in-tass-web-with-communication-rules-enabled) TASS documents which have different possible address number setups. In addition I have seen schools with different numbers of emergency contacts or fee copy addresses, or using a different numbering scheme entirely.

As such, you may wish to consider some configurability per school regardless of if you can use address descriptions or numbers to match on.

**Comment by cwool** [comment]
Thanks for the extra information. 

We are currently planning to make this flexible per school but will still need the address number added to the api in order to find the correct address, as the description is too variable compared to numbers.

**Comment by akaddo** [comment]
We want the same feature to be available as well.
We posted on the TASS forum if you would like to vote [here](https://forum.tassweb.com.au/t/getcommunicationrulesdetails-api-enhancement/4344?u=akaddoura).
