### ISSUE TITLE
Student Contact Details

### ISSUE THREAD

**Issue by AdelineOptimo** [TheAlphaSchoolSystemPTYLTD/student-details#4]
Hi,

A couple of questions regarding the contact details returned by the getCommunicationRulesDetails method:
- can you confirm that the email field always return 1 email address? or is it possible to have multiple comma separated emails? 
- do you have the address details, currently returned in the "current_address" field as separated values (address, suburb, state, postcode, etc)?
- how many email addresses does TASS hold for each student? and is it possible for the API to return these as flat information for the student? e.g. getStudentsDetails method to have email_1, email_2, ... email_x under "general_details"

Thanks.

**Comment by jtc** [comment]
> address details, currently returned in the "current_address" field as separated values (address, suburb, state, postcode, etc)

+1 for this request

**Comment by tassweb-talon** [comment]
already done
