### ISSUE TITLE
Permission Roles

### ISSUE THREAD

**Issue by i-am-ari** [TheAlphaSchoolSystemPTYLTD/student-details#43]
The Student Module can store Personally Identifiable Data such as Drivers Licenses, Passports, etc. and health records.

Would it be possible for this API (and the Employee/HR API) to have a permission role placed over it in the TASS software down to the permission point to only allow certain fields to be pulled through the API? This would prevent intermediary supply chain companies (such as Wonde) from trying to pull super sensitive data fields.

**Comment by bradftass** [comment]
Hi,  The Student Details API is currently a Version 3 API.  This means you can associate a Permission Role for the API itself.  Within that role, you can allocate certain permissions that will restrict the data returned based on the Role that is noted in the API Documentation.

E.g. Student Details API > getMedicalGeneral endpoint uses the "Medical Setup > Student Medical > View" permission point.  If the role that you allocate to this API did not have that permission set, the data associated with this endpoint would not be returned.

Unfortunately, it is not as granular as you mentioned regarding limiting specific fields in the return call.

Currently the Employee / HR API is version 2 and does not include this level of permission based restriction yet.

I hope this helps.
