### ISSUE TITLE
Add support for paging

### ISSUE THREAD

**Issue by rutger-koperdraad** [TheAlphaSchoolSystemPTYLTD/student-details#54]
The method getStudentsDetails returns all student records, but when photos are included, that easily gets too much to handle in a single call. That is what actually happened for an integration that I am working on. This can be solved partially by using update_on_from, but when large amounts of data are uploaded to TASS in a short interval, this option is not enough. What we need is support for paging, that is, downloading the data in muyltiple manageable chunks of which the maximum number of records can be specificied in the request.

**Comment by justin-dx** [comment]
+1
This is what the project I was working on ran into as well, being able to request paged data from all endpoints (the parent details one is also big) would be a nice feature.

**Comment by leonseremelis-tass** [comment]
Thank you for your inquiry. Currently, paging is not supported, but rest assured, we are actively considering its implementation for a future release.

**Comment by scottetass** [comment]
Hi,

Paging won't be implemented in the near future for this endpoint.

As you have pointed out, you can use the update_on filtering to restrict records or any of the other filters available such as campus, year group etc. There is also the option of passing in a list of student codes, if you know them up front.

I understand that is not ideal but at the moment, paging would be a big change to the endpoint which is not on the radar any time soon.
