### ISSUE TITLE
Does address_person_posn = sfa_num?

### ISSUE THREAD

**Issue by cwool** [TheAlphaSchoolSystemPTYLTD/student-details#60]
Does the "address_person_posn" from getCommunicationRulesDetails (student-details) will always equal the "sfa_num" from getParents (idm)?

We're trying to match a username from the getParents method using the parent codes but need to take into account the sfa_num for split families. Do these values match up? Alternatively, are "m_username" and "f_username" fields possible?

**Comment by leonseremelis-tass** [comment]
Hi, the 'address_person_posn' refers to the 'Person Posn' field that is displayed in Parent Records > Parent Records Setup > Addresses tab in TASS. This might be adequate for what you are trying to achieve.
