### ISSUE TITLE
Turn on Photo sync for Wonde dev environment

### ISSUE THREAD

**Issue by cwool** [TheAlphaSchoolSystemPTYLTD/student-details#61]
Hi,

The getStudentsDetails method doesn't let us sync photos when using the parameter even when I've uploaded a test photo. Can we have this fixed? Cheers.

URL: https://api.tassweb.com.au/tassweb/api

Company: 30

App code: WONDESD

**Comment by cwool** [comment]
Hi Leon,

Parameters passed:
{"currentstatus":"current","includephoto":"true"}

Error received:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<title>404 - File or directory not found.</title>
	<style type="text/css">
		
	</style>
</head>

<body>
	<div id="header">
		<h1>Server Error</h1>
	</div>
	<div id="content">
		<div class="content-container">
			<fieldset>
				<h2>404 - File or directory not found.</h2>
				<h3>The resource you are looking for might have been removed, had its name changed, or is temporarily
					unavailable.</h3>
			</fieldset>
		</div>
	</div>
</body>

</html>
{"__status":"invalid","__forms":{"includephoto":{"options":"","type":"bool"},"thumbnail":{"options":"","type":"bool"},"currentstatus":{"required":true}},"__msg":"Not
Found","__invalid":{},"__locks":{}}

Regarding the configuration options, everything is greyed out, so we're probably restricted from this settings page to enable the photos. Happy to do the steps mentioned if you make our account have access to these screens. Screenshot attached for reference. 
<img width="1556" alt="Screenshot 2023-08-10 at 5 09 17 pm" src="https://github.com/TheAlphaSchoolSystemPTYLTD/student-details/assets/70622121/d220a86a-bf2d-4e5d-8dc3-41fa47285b90">

**Comment by cwool** [comment]
Hi, photos have now been turned on but having a different error now. When doing the getStudentsDetails call with params {"currentstatus":"current","includephoto":"true", "year_group":"12"} I get the error below:
				<h2>404 - File or directory not found.</h2>
				<h3>The resource you are looking for might have been removed, had its name changed, or is temporarily
					unavailable.</h3>

When trying the year 12 who I've added a photo to with the parameters {"currentstatus":"current","includephoto":"true", "code":"20076"} I am able to get the student and the photo back correctly.

Why am I getting an error message when there is at least one photo attached? Shouldn't the first call just return photo as empty except for this one student instead of failing? Or is there something else at play here?

Help on this would be much appreciated as it's the last hurdle getting the photos syncing in batches of year levels.

**Comment by leonseremelis-tass** [comment]
The default behaviour if a student photo does not exist is to retrieve the default Unavailable.gif image. It seems like this might be missing in your case, I will follow up on this and let you know.

**Comment by cwool** [comment]
Hi Leon, we're still getting the 404 error. Could you please follow up on this and let me know when it's resolved?

**Comment by leonseremelis-tass** [comment]
Ok, I see there was still an error coming onto the logs for cmy 30. I have added the default .gifs there so can you try again and let me know how you go?
