### ISSUE TITLE
Tass UI for address_person_posn

### ISSUE THREAD

**Issue by igroenewald** [TheAlphaSchoolSystemPTYLTD/student-details#63]
Hi Support,

To which field in the Tass user interface does the "address_person_posn" field map to?

Thanks

**Comment by leonseremelis-tass** [comment]
Hi, thanks for your question. The 'address_person_posn' refers to the 'Person Posn' field that is displayed in Parent Records > Parent Records Setup > Addresses tab in TASS.

**Comment by igroenewald** [comment]
Got it, thanks for the help.
