### ISSUE TITLE
How retrieve the student details without any rest API endpoint URL

### ISSUE THREAD

**Issue by PraveenRelli992** [TheAlphaSchoolSystemPTYLTD/student-details#64]
I am trying to retrieve the student details by using the sample get URL provided in student details API documentation. but I am not able to retrieve the student using sample get URL. While I was trying to retrieve the student, I am facing error is "remote name could not be resolved".

can you please provide exact endpoint URL for retrieving student details.

**Comment by leonseremelis-tass** [comment]
Details on how to connect to the API can be found here:
https://github.com/TheAlphaSchoolSystemPTYLTD/api-introduction/blob/master/README.md
