### ISSUE TITLE
Return current address in structured form

### ISSUE THREAD

**Issue by tambrose-pacl** [TheAlphaSchoolSystemPTYLTD/student-details#66]
Hi there,

Is is possible to update the getCommunicationRulesDetails API to return current address information in a structured way? The 'current_address' property is optimised for text rendering, and therefore is poor for data processing.

I am currently having to rely on regex and array splitting to separate address information into 'Address Line 1 - 4', 'Suburb', 'Postcode' and 'Country'. This method is not as reliable as I would like, since it is hard to handle an address like this

Regatta Apartments `<br />` Unit 3 `<br />` 99 Pretend St  `<br />` SUBURB NAME QLD 4000 `<br />` AUSTRALIA

You can work backwards with splitting on `<br />` and `<spaces>` but what if a returned address does not contain the country? Then all of the expected properties shift a position.

I am sure a person more confident with regex than me could work it out but hopefully a minor update to the API means that would not be necessary.

In the TASS UI address information is broken up this way so it seems straight-forward to present this information in the API the same way?

Thanks,

Tim

**Comment by leonseremelis-tass** [comment]
Hi Tim,

Thank you for your feedback. Your suggestion to update the getCommunicationRulesDetails API to return address information in a more structured way is indeed a good one.

I agree that having the address information broken down’ would improve the data processing capabilities and reduce the reliance on regex and array splitting.

I will propose this enhancement to our development team. We always strive to improve our API based on user feedback, and your input is greatly appreciated.

**Comment by scottetass** [comment]
Hi Tim,

The breakdown of the address individual fields will be in the 59.12.200 release.

Thanks, Scott
