### ISSUE TITLE
Map data to Tass GUI

### ISSUE THREAD

**Issue by igroenewald** [TheAlphaSchoolSystemPTYLTD/student-details#67]
Hi Support,

From the getCommunicationRulesDetails end point, could you please advise where in the Tass UI the below fields are populated? A screen print would be very helpful if possible.

- m_surname
- m_first_name
- f_first_name
- f_surname

Thanks

**Comment by scottetass** [comment]
Hi,

These fields come from the students' parents - m_???? relates to the mother (or parent 1), f_???? relates to the father (or parent 2).

You can see those details by looking under Student Admin / Parent Records / Parent Information / Parents menu, find the appropriate parent details, then go in to edit mode and click 'Edit' beside the mother or father name.

Another way, is to view the parent record through Community Plus UI

If you provide me an email, I can send through those screenshots as well.

Thanks.

**Comment by igroenewald** [comment]
Hey,

Thanks for the info. It is extremely helpful.
That would be great, email address: igroenewald@wonde.com

Thanks
