### ISSUE TITLE
getCommunicationRulesDetails end point timeout

### ISSUE THREAD

**Issue by igroenewald** [TheAlphaSchoolSystemPTYLTD/student-details#69]
Hi Support,
We're trying to sync student parent records for one of our schools but the request keeps timing out. Can you see what could by causing this? Details are as follows:

School: St Luke's Anglican School
Endpoint: https://kiosk.stlukes.qld.edu.au/tassweb/api/?appcode=WONDESTUD&v=3&method=getCommunicationRulesDetails&company=02&token=<omitted>

Response (extract):
kiosk.stlukes.qld.edu.au | 524: A timeout occurred
The origin web server timed out responding to this request.

Please let me know if more information is needed.
Thank you

**Comment by scottetass** [comment]
Hi,

What version of TASS do you have installed?

There was a performance related change in 59.07.200 for this particular endpoint.

Thanks, Scott

**Comment by igroenewald** [comment]
Hi Scott,
It is my understanding that they host their own TASS Server. They are on v01.059.07.200.
Thank you

**Comment by scottetass** [comment]
Hi,

Can you try the call again, noting down the time the call started and how long before it timed out? This info will help me investigate the issue you are experiencing.

Also, if you can provide the parameters that are being used.

Thanks, Scott

**Comment by igroenewald** [comment]
Hi Scott,
Most certainly. Start: 14:45. End: 14:46. Duration: 1m40s.
Parameters: {"currentstatus":"current","commtype":"all"}

I've also attached a screen print of Postman, showing the result.

Let me know if there is anything else you need.

Thanks
![Screenshot 2024-08-15 at 2 47 28 PM](https://github.com/user-attachments/assets/a8aa320d-6faa-48d8-8427-d206f46cf5f6)

**Comment by igroenewald** [comment]
Hi Scott,
For your info, the school have updated their version of Tass today (Thursday, 15 Aug) to 59.8.200.
Regards

**Comment by igroenewald** [comment]
Hi Scott,
Apologies for the dribs and drabs. The school have asked if it is possible to add them to this support ticket. They offered to assist with any troubleshooting need by Tass at their end.
Their contact is Shane Hannant and email address: doict@stlukes.qld.edu.au
Thank you
Irene

**Comment by scottetass** [comment]
Hi Irene,

Shane has discovered the issue of timing out lies outside of TASS and will be attempting some work arounds on their end to overcome the timeout problem.

This particular endpoint has recently gone through some performance improvements and greatly cut down execution times but for some schools, the large amount of data to return in a single call is the real problem. We may have to revisit this call at a later stage for further enhancements if it continues to cause issues for schools.

Thanks, Scott

**Comment by igroenewald** [comment]
Hi Scott,

Thank you for the update. We have another school with a similar problem. Worth noting this school's Tass instance is also local. I will create a new ticket for their issue.

Thanks for all your help
Irene
