### ISSUE TITLE
UD Areas

### ISSUE THREAD

**Issue by jtc** [TheAlphaSchoolSystemPTYLTD/student-details#7]
Can we please have a way to extract information from Student UD Areas in this API?

**Comment by pl4nty** [comment]
We have a significant in-house product reliant on database views to get this info, would love to migrate to APIs. TASS Cloud isn't so appealing when we need to use a VPN for data access...

**Comment by jtc** [comment]
Resolved in #29 / version 52.2.000 (IMS 180870), thank you!
