### ISSUE TITLE
'adressee' typo: getCommunicationRulesDetails

### ISSUE THREAD

**Issue by jtc** [TheAlphaSchoolSystemPTYLTD/student-details#8]
Very minor issue, just wanted to note that 'addressee' seems to be mistyped as 'adressee' in the API response for getCommunicationRulesDetails

**Comment by jtc** [comment]
Just looking at other issues, I noticed this was also mentioned in #3

**Comment by ricardorusson** [comment]
To ensure backwards compatibility we will be releasing an update with an additional 'addressee' return value.

The erroneous 'adressee' will be depreciated, and removed at a later date.

**Comment by ricardorusson** [comment]
Fixed in #18
